

if (NOT WIN32)
    return()
endif()

if ("${targetType}" STREQUAL "EXECUTABLE")
    set(TARGET_TYPE_APP 1)
elseif ("${targetType}" STREQUAL "SHARED_LIBRARY")
    set(TARGET_TYPE_DYNAMIC_LIB 1)
elseif ("${targetType}" STREQUAL "STATIC_LIBRARY")
    set(TARGET_TYPE_STATIC_LIB 1)
endif()

set(FILE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(FILE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(FILE_VERSION_PATCH ${PROJECT_VERSION_PATCH})
set(FILE_VERSION_TWEAK ${PROJECT_VERSION_TWEAK})

set(PRODUCT_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(PRODUCT_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(PRODUCT_VERSION_PATCH ${PROJECT_VERSION_PATCH})
set(PRODUCT_VERSION_TWEAK ${PROJECT_VERSION_TWEAK})

set(ORIGINAL_FILE_NAME ${targetRuntimeFileName})

configure_file("${rcInFile}" "${rcOutFile}" NEWLINE_STYLE WIN32)
